### ISSUE TITLE
Add a RSS feed

### ISSUE THREAD

**Issue by StoicLoofah** [tdeck/sfhacks#1]
I'm not sure if a lot of other people are still using RSS feeds, but I do, and it would be convenient to have updates on upcoming hackathons via my RSS reader rather than having to check the website specifically.

In any case, thanks for building this! I actually went to my first hackathon (the baseball hack day) a few weeks ago because I saw it on your site, so it's really handy!

**Comment by tdeck** [comment]
Hey, glad you're finding the site useful! I just hacked together a very basic Atom feed, you can find it at at https://sfhacks.com/index.atom. Does that work for you?

**Comment by StoicLoofah** [comment]
Looks great. Thanks for adding that so quickly!
